name: Run CICD

on: workflow_dispatch

jobs:
  run-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Make Command Action
        uses: teesher/actions_playground/make_action@main
        with:
          command: 'print-hello'

      - name: Run Make Command Action Using Non-Standard Makefile
        uses: teesher/actions_playground/make_action@main
        with:
          command: 'print-hello'
          makefile: OtherMakefile
